## Docker Compose for development
version: "3"
services:
  redis:
    image: redis:6
    container_name: clayton-redis
    ports:
      - 6379:6379
    volumes:
      - clayton-redis:/data

volumes:
  clayton-redis:
